services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    CoreShop2VueStorefrontBundle\EventListener\ProductListener:
        tags:
            - { name: kernel.event_listener, event: pimcore.dataobject.postUpdate, method: postSave }
            - { name: kernel.event_listener, event: pimcore.dataobject.postAdd, method: postSave }

    CoreShop2VueStorefrontBundle\EventListener\CorsListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 300 }

    CoreShop2VueStorefrontBundle\EventListener\OnRefreshTokenResponseListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 400 }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: 410 }

    CoreShop2VueStorefrontBundle\EventListener\OnAuthenticationSuccessListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: attachModifyResponse, priority: -1 }

    CoreShop2VueStorefrontBundle\EventListener\OnAuthenticationFailureListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_failure, method: attachModifyResponse, priority: -1 }