imports:
  - { resource: events.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    _instanceof:
        CoreShop2VueStorefrontBundle\Bridge\DocumentMapperInterface:
            tags: ['coreshop2vuestorefront.document_mapper']

    CoreShop2VueStorefrontBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    CoreShop2VueStorefrontBundle\Bridge\DocumentMapper\DocumentProductMapper: ~

    CoreShop2VueStorefrontBundle\Bridge\DocumentMapper\DocumentCategoryMapper: ~

    # CoreShop2VueStorefrontBundle\Bridge\DocumentMapper\DocumentAttributeMapper: ~

    # CoreShop2VueStorefrontBundle\Bridge\DocumentMapper\DocumentConfigurableProductMapper: ~

    CoreShop2VueStorefrontBundle\Bridge\Attribute\AttributeIdGenerator: ~

    # CoreShop2VueStorefrontBundle\Bridge\Attribute\AttributeResolver: ~

    CoreShop2VueStorefrontBundle\Bridge\Helper\DocumentHelper: ~

    CoreShop2VueStorefrontBundle\Bridge\Helper\PriceHelper: ~

    CoreShop2VueStorefrontBundle\Bridge\DocumentMapperFactoryInterface:
        alias: CoreShop2VueStorefrontBundle\Bridge\DocumentMapperFactory
    CoreShop2VueStorefrontBundle\Bridge\DocumentMapperFactory:
        arguments:
            - !tagged_iterator 'coreshop2vuestorefront.document_mapper'

    CoreShop2VueStorefrontBundle\Bridge\RepositoryProvider: ~

    CoreShop2VueStorefrontBundle\Bridge\ImporterFactory: ~

    CoreShop2VueStorefrontBundle\Bridge\Response\ResponseBodyCreator:
        arguments:
          - '@coreshop.repository.index'

    CoreShop2VueStorefrontBundle\Bridge\Response\Order\OrderResponse:
        arguments:
          - '@coreshop.repository.index'

    CoreShop2VueStorefrontBundle\Bridge\Response\Cart\CartResponse:
        arguments:
          - '@coreshop.repository.index'

    CoreShop2VueStorefrontBundle\Security\User\UserProvider:
        arguments:
            - "@coreshop.repository.customer"

    CoreShop2VueStorefrontBundle\Bridge\Customer\CustomerManager:
        arguments:
            - "@coreshop.factory.customer"
            - "@coreshop.factory.address"
            - "@coreshop.customer.registration_service"
            - "@coreshop.repository.country"
            - "@coreshop.repository.customer"

    CoreShop2VueStorefrontBundle\Bridge\Order\AddressDataToAddressItemTransformer:
        arguments:
            - "@coreshop.factory.address"
            - "@coreshop.object_service"
            - "%coreshop.folder.address%"
            - "@coreshop.repository.country"

    CoreShop2VueStorefrontBundle\Bridge\Order\OrderManager:
        arguments:
            - "@coreshop.factory.order"
            - "%coreshop.folder.order%"
            - "@coreshop.object_service"
            - "@coreshop.factory.order_item"
            - "@coreshop.state_machine_applier"
            - "@coreshop.order.transformer.cart_to_order"
            - "@coreshop.repository.customer"

    CoreShop2VueStorefrontBundle\Bridge\PersisterFactory:
        arguments:
            $elasticsearchConfig: '%core_shop2_vue_storefront.elasticsearch_config%'
            $stores: '%core_shop2_vue_storefront.stores%'
            $storeRepository: '@coreshop.repository.store'
            $storeAware: '%core_shop2_vue_storefront.store_aware%'

    CoreShop2VueStorefrontBundle\Command\IndexCommand:
        tags: ['console.command']

    CoreShop2VueStorefrontBundle\Bridge\Cart\CartContext:
        arguments:
            - '@coreshop.context.customer'
            - '@coreshop.context.store'
            - '@coreshop.repository.cart'
            - '@pimcore.http.request_helper'
        tags:
            - { name: coreshop.context.cart, priority: 100 }
