core_shop_product:
  pimcore:
    product:
      classes:
        repository: CoreShop2VueStorefrontBundle\Repository\ProductRepository
    category:
      classes:
        repository: CoreShop2VueStorefrontBundle\Repository\CategoryRepository