lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem' # required for token creation
    public_key: '%kernel.project_dir%/config/jwt/public.pem'  # required for token verification
    pass_phrase: 'admin' # required for token creation, usage of an environment variable is recommended
    token_ttl:  3600
    token_extractors:
        authorization_header:
            enabled: true
            prefix:  Bearer
            name:    Authorization

        query_parameter:
            enabled: true
            name: token